### ISSUE TITLE
Requiring organizers to publish scrambles after the round or group has ended

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#877] opened 2019-11-15 18:26 UTC
One issue with misscrambles or repeat scrambles is they often aren’t caught until after the competition. Publishing scrambles after they were no longer in use could be helpful since competitors could catch misscrambles, prove to the delegate that they received a misscramble and receive and extra. 

The main issue I see with this is being able to release the scrambles. Scrambles would likely have to be printed out for competitors since not all of them will have access to the internet. They could additionally be shared online so that fewer copies would need to be printed.

**Comment by xsrvmy** [comment] 2019-11-15 19:27
This is probably only useful if the scramble signature is missing.
I think this only works in a NA/European comp style. I've been to a comp in China where scramble groups are much less defined and can change mid-average.

**Comment by dancing-jules** [comment] 2019-11-15 23:23
> where scramble groups are much less defined and can change mid-average.

Is that even legal? That sounds chaotic and like a recipe for problems.

**Comment by xsrvmy** [comment] 2019-11-16 02:06
Nothing in the regulations says the scrambles have to be from the same group.
I'm actually not sure what they do about scramble groups. Maybe two scramble groups are active at the same time. The competitor does not know which group he/she is in though.
Even in the common format though if a competitor is really slow or arrives late for the group, he/she might receive the last one or two scrambles from the next group depending on organization.

**Comment by Ivan-Brigidano** [comment] 2019-11-16 16:57
I think making it a requirement conditions a lot to organizers because of logistical problems. However it could become a recommendation

**Comment by xsrvmy** [comment] 2019-11-20 07:16
Actually I think part of the problem is the increase in scramble accountability meant that a delegate has to give the password for a scramble check for a past round. This could be fixed by making the password one time (for example, generating a password-protected zip file for each PDF instead of putting the password on the PDF)

**Closed as completed** 2020-04-20 19:49 UTC
