### ISSUE TITLE
Disallow 2Xw type moves on FMC

### ISSUE THREAD

**Issue by GuidoDipietro** [thewca/wca-regulations#947] opened 2020-01-02 17:17 UTC
To all the Regulations Committee,

I have recently come to notice the moves in the set {2Uw, 2Fw, 2Rw, 2Dw, 2Bw, 2Lw} as well as their double and counterclockwise correspondents are still a thing in FMC notation after the 2020 changes.

This is completely unnecessary and should have been removed together with [r] moves and all the rest.

Argument:
The point of removing an number of legal moves from the official FMC moveset was making proofreading more simple, and avoiding confusions to beginners, as well as uniforming the notation in general.
Every "duplicate" move was in a way made redundant, such as [r] = x, or previously the fact that U2' = U2.
In spite of that, moves of the sort of 2Xw, such as 2Uw, 2Rw', 2Fw2, etcetera, were deliberately kept for a reason I am still to understand.
They take up extra space, are difficult to understand, and will *never* be used in an attempt by anyone seriously.

I have been cubing since 2007 and officially since 2013, and I had never come across any sound cuber using such a notation for 3x3, and I believe this is just a pointless extension of big cube notation to 3x3 that shouldn't have been kept.
My thought process when I saw those were:
"Hm, 2Uw... What is this? If 3x3 was a big cube this would just be Uw, but we already have Uw for that... I guess that's not what it is, it might be something else!"
And I believe many would go through a same reasoning and arrive at a false conclusion.

Furthermore, I can imagine many experienced but somewhat still "new" cubers mistakenly reading 2Uw as Uw2, and I wouldn't blame them for that.

Please consider removing those as part of the big FMC notation refactor as it, I repeat myself, makes no sense at all to keep them.

Would you also allow 2Uw for 2x2 rotations?

If I am missing on some key aspect that makes these moves useful in any way please make me notice.

Thanks for the read.

**Comment by alexmaasswca** [comment] 2020-01-02 17:33
I'm pretty sure the vast majority of delegates off the top of their head would say that 2Xw type moves are not allowed. 

Also, if these 2Xw moves are removed, we can finally list every move allowed on FMC on the FMC sheet!

**Comment by Goosly** [comment] 2020-01-02 18:17
Duplicate of https://github.com/thewca/wca-regulations/issues/946

**Comment by lgarron** [comment] 2020-01-05 01:18
Closing as a duplicate of #946!

**Closed as completed by lgarron** 2020-01-05 01:18 UTC
