### ISSUE TITLE
Pillowed cubes revisit

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#458] opened 2017-08-24 14:52 UTC
https://www.worldcubeassociation.org/regulations/#3h1

I don't see why this is a problem anymore. They were originally only disallowed because people believed they shared the same or similar traits to stickerless cubes, however these are allowed now. I don't see any reason why we shouldn't allow pillowed puzzles? We have concave puzzles, for example the wingy skewb, the concave megaminx. We allow bubbled stickerless cubes like the YuHu megaminx. Removing this regulation doesn't seem like a detriment.

**Comment by Laura-O** [comment] 2017-09-14 11:42
Duplicate of #195, please continue the discussion there.

**Closed as completed by Laura-O** 2017-09-14 11:42 UTC
