### ISSUE TITLE
Standard protocol for important proposed changes.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#106] opened 2013-12-08 01:31 UTC
See [the proposal at issue #39](https://github.com/cubing/wca-documents/issues/49#issuecomment-30072168) for an example.

Something like:
- Proposed change
  - Preferably with exact wording changes in the form of a diff.
- Pros
- Cons
- Community concerns?
  - What is the main support/dissent?
  - If this goes against a significant portion of the community, what is the overriding justification?

**Comment by DeneBeardsley** [comment] 2013-12-15 07:36
## Procedure for proposing significant changes to the WCA regulations

I don’t believe this is a process that belongs in the regulations, so there is nothing to compare it to, and nor does it need to be put specifically in the format of the regulations.
1. A serious proposal for a regulation change is put forward by a member of the community. [e.g. delegate, WRC member, random member of the community]
2. If the WRC determines the proposal to be in the category of “significant”, they formally acknowledge the proposal publicly, and the wider community is consulted to gather all the opinions on the matter, and to gain a general idea of how the community feels about the proposal. [timeframe? how to manage all the input/data?]
3. Special input is gathered from WCA Delegates for "expert" opinion, and preferably to represent the opinions of their respective countries. [timeframe?]
4. The WRC gather all arguments for and against the proposal, and determine whether to accept or reject the proposal.
5. If accepted, the WRC draft a specific proposal. [in terms of changes to the regulations]
6. The WRC submit the proposal, with the arguments for and against, to the WCA Board for a vote.
7. The majority vote of the WCA Board determines the final outcome. In the case of a tie the proposal is rejected.
8. The WRC formally announce the final outcome of the process, including the reasoning that lead to the final decision.

## Additional procedures for proposing the addition or removal of an event

I don’t believe the above procedure is enough for the biggest of decisions: adding or removing events. I propose the following modifications for this specific case:

Step One: The WCA comes up with a specific vision as to the sorts of events it would like to have. Some things to consider:
- Simplicity vs complexity
- Originality/uniqueness vs similarity
- Popularity vs “cliques” (as in, catering to the masses, or giving the minorities something as well)
- Practicality for holding in competition vs not worrying about being time/resource consuming
- Easy to fit in with current regulations vs having to come up with a whole new subset of regulations
- Easy to regulate in competitions vs being labour intensive / controversial (I have magics in mind here)

Step Two: Follow the above procedure as for any other regulation change, with the final outcome resulting in the removal of the event, or in the case of adding events, a trial period.

Step Three: Follow these additional procedures:
9. If the proposal for the addition of an event is accepted, an eleven month trial period is initiated as of the first of January the next year. During this trial period all results are recorded and entered into the database as usual, however all results are provisional, dependent on a review conducted by the WRC at the end of the trial period. Also, during this trial period there is no recognition of records (WR, CR, NR).
10. At the end of the eleven month trial period, the WRC conduct a review of the event over a period of one month. This review will gather input from the wider community, delegates, and the WCA Board. The review will look at whether the event is fulfilling the vision of the WCA as defined in Step One, as well as considering any negative feedback received. During the review the event can still be held at competitions.
11. The final outcome of the review with determine whether the event is rejected, or accepted fully as a WCA event along with any modifications to the regulations that may be introduced. This must be publicly announced before the end of the year.
12. If accepted, any modifications to the regulations, as well as the recognition of records as of the end of the trial period, will begin from the first of January the next year.

## Pros
- This procedure involves people at all levels of the organisation giving input, including the wider community, delegates, the WRC, and the Board.
- All members of the community are encouraged to voice their ideas for improving the regulations and the operations of WCA competitions in general.
- The community is kept informed of the considerations of the WRC, and also the final outcomes of those considerations
- Specifically regarding the addition of events: because there is initially a trial period, there is extra time for delegates to become accustomed to the new event, therefore there won’t be an issue with sudden additions of events (as the sudden addition of skewb with short notice was clearly not well received).
- Specifically regarding the addition of events: the trial period will avoid the perceived issue of “the rush of new records” that comes with a new event.

## Cons
- Ultimate power is given to the few members of the Board, whom are not a democratically elected representative group, and therefore may be perceived as not considering the voice of the community.
- Potentially time consuming.
- There are still a lot of judgement calls to be made along the way; the problem is it would be difficult to come up with a system that relied on less vague measurements (e.g. 70% must vote in favour) while still maintaining fairness for everyone.
- Specifically regarding the addition of events: I suspect that people simply aren’t going to like with the concept of a trial period, and the lack of recognising records for that period.

## General thoughts
- It may be time consuming, but this is kind of what happens already anyway. I’m not sure what suitable timeframes would be for community discussion; some topics will stay alive for a while, but others die fairly quickly. I think 2 weeks would be a suitable allowance, although others might think differently and I’m not fussed, as long as there is enough time. 
- I think the trial period is a good idea, despite my concerns that it wouldn’t be well received. I believe we should be thinking long term, and one year is not a long time in the greater scheme of things. 
- I’ve tried to avoid being wordy, although things got a little out-of-hand for steps 9-11. These could do with some serious re-writing if the ideas are well received.

**Comment by Laura-O** [comment] 2017-09-14 11:03
The way we do regulation changes and the way we discuss them with WCA staff has significantly changed since 2013, so I'm closing this for now.

**Closed as completed by Laura-O** 2017-09-14 11:03 UTC
Labels: formatting
