### ISSUE TITLE
Revert to Old Clock Notation

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#117] opened 2013-12-12 04:02 UTC
I brought this up a couple times at worlds, and after running/participating in several competitions since then, my stance on clock notation has been cemented even further: we should return to the old Jaap notation.  My two main reasons for this are:
- Jaap notation is used on almost every scrambling/timing program available.  To my knowledge, the WCA notation is only available through TNoodle, which is not suitable for practicing.  As a result of this, the fastest clock solvers are not suited to this notation and are significantly slower at scrambling this way.  
- The new WCA notation was designed to be easy for beginners to learn.  I have found this to not be the case, and instead I end up getting pushed through my average so I can scramble and speed up the event.  I cannot remember a time where there has been someone capable of scrambling a clock at a regional competition that wasn't competing in the event, which is frustrating since there is often only one scrambling group.

Since the notation isn't any easier for beginners to learn, we still have the fastest clock solvers doing the scrambling.  For this reason, it makes sense to give the people who solve clock notation that they use when practicing to make running clock smoother.

**Comment by lgarron** [comment] 2013-12-12 04:04
Duplicate of #60. Could you move your comment there?

**Closed as completed by lgarron** 2013-12-12 04:04 UTC
