### ISSUE TITLE
Bring back old clock scrambling notation?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#60] opened 2013-08-03 02:34 UTC
All of the clock solving pros I've talked to dislike the new notation. They say that the old notation was familiar and they were fast at scrambling it because the pin order was natural to them. By changing the notation, it's added more confusion and makes scrambling take more time. Despite the new notation being slightly easier to understand, it doesn't seem to be helpful at competitions because most of the scramblers are good at using the old notation. 

Additionally, many people have said that the old notation was easier to teach to non-clock solvers. Also, many of the popular online puzzle timers still use the old notation, so you can't easily generate clock scrambles using the current WCA notation, to use during practice sessions.

I personally like the new notation (probably because I didn't practice too much with the old one), but the vast majority of clock solvers I've talked to dislike it, and would much prefer the old notation.

**Comment by pedrosino** [comment] 2013-08-03 17:11
I'm a clock solver, and didn't find it hard to adapt to.
Clock scramblers who aren't solvers are usually pretty bad, so whatever is easy for non-clock people is better.

**Comment by lgarron** [comment] 2013-08-04 04:44
Indeed, the point was to make it as easy as possible to do the right thing, even if you only kind of know what you're doing. This is critical for competitions who offer clock and don't have too many resources (i.e. fast people who are not too busy competing to scramble).

Today, Daniel Sheppard suggested bringing back the old scrambles and adding a key to the top of the page. I'm not opposed to this, but someone would need to make it (an .eps or .svg file would probably do).

No matter what we do, I think this change should be made on empirical evidence. Now that we've used both the old and the new notation, we should ask delegates, organizers and competitors about their experiences.

**Comment by sarahstrong314** [comment] 2013-08-29 00:56
What do you think of Stefan's design for displaying both scrambles?
http://www.speedsolving.com/forum/showthread.php?43327-WCA-Clock-Notation-Discussion&p=894714&viewfull=1#post894714

I think it would be great, although I think there should be more separation between the two scrambles, ideally a dotted line.

**Comment by lgarron** [comment] 2013-08-29 02:16
I'm strongly against printing two different kinds of scrambles. It doesn't simplify anything, and I'm not sure we could even get evidence that it's much more useful.

**Comment by lgarron** [comment] 2013-12-08 19:35
Sarah, could you take the lead on this?

I would definitely prefer that we keep only one official notation. If someone feels very strongly otherwise, I would like them to update TNoodle to support multiple clock notations at once, or find someone to do it. I don't want to ask Jeremy to do this just because some people might like it more.

I don't think we should care specifically about clock solving pros, except those that scramble at official competitions. And since it helps to keep the Regulation changes consistent, I don't think we should switch back unless we believe it will improve things significantly.

**Comment by lgarron** [comment] 2013-12-11 02:54
Ping.

**Comment by SAuroux** [comment] 2013-12-11 08:13
I'm definitely in favour of either use both notations or keep the current one. Most complaints about the new notations we got after introducing it have already vanishhed these days.

**Comment by LorenzoVP** [comment] 2013-12-11 11:12
I think the current notation is really clear. I got a positive feedback from a lot of cubers at the last Italian competition: we used to have like 2-3 scramblers in the past because nobody knew how to scramble clock, this time we had 6 guys willing to scramble it. I don't think this is due interely to the new notation, but it surely helped.

**Comment by KitClement** [comment] 2013-12-12 04:06
Reposting from #117 here, sorry that I didn't see this issue first.

I'm still finding the new notation somewhat difficult to work with and I'd like to revert to the old notation.  My two main reasons for this are:

Jaap notation is used on almost every scrambling/timing program available. To my knowledge, the WCA notation is only available through TNoodle, which is not suitable for practicing. As a result of this, the fastest clock solvers are not suited to this notation and are significantly slower at scrambling this way.

The new WCA notation was designed to be easy for beginners to learn. I have found this to not be the case, and instead I end up getting pushed through my average so I can scramble and speed up the event. I cannot remember a time where there has been someone capable of scrambling a clock at a regional competition that wasn't competing in the event, which is frustrating since there is often only one scrambling group.

Since the notation isn't any easier for beginners to learn, we still have the fastest clock solvers doing the scrambling. For this reason, it makes sense to give the people who solve clock notation that they use when practicing to make running clock smoother.  I see no real benefit in the current notation.

**Comment by lgarron** [comment] 2013-12-12 04:15
Legitimate question: what should be our primary reason for making one choice over another?

We have perhaps three kinds of cubers, who all have different ideas of what clock notation would be the best:
- Clock pros
- Experienced competitors and organizers
- Most competitors

I've heard very mixed opinions about the new notation from all of them, including significant favor of the new one.

I don't have time to spend on this issue myself, but the first thing I would do is a delegate poll. Unfortunately, "Should we switch back? (yes/sure/no)" doesn't tell the whole story. I'd really like to hear how the new notations has worked for delegates from small international competitors, rather than the just hearing from the vocal people.

**Comment by SAuroux** [comment] 2013-12-12 08:11
Adressing Kit's post: The argumentation is simply invalid by logical means,
sorry. The fact that people are too lazy to get in touch with the new notation
does provide no information at all about the question if the new notation
is easier to learn for beginners than the old one.

The new notation is definitely easier to learn. I got this confirmed by
so many people by now. I'm myself able to scramble fast now by using it at
competitions only. We should rather do some lobby work to make sure that
our notation finds its way into some scrambling programms instead of going
a step back in 2014.

As a side node, you should really be doing more than 1 scrambling group for clock. Of course you will end up with problems if not doing so. The same goes for Megaminx and SQ1.

2013/12/12 Lucas Garron notifications@github.com

**Comment by KitClement** [comment] 2013-12-12 08:35
If there is only one round of clock, I (among other delegates here) will only use one group, as suggested in the regulations.  I know it's not mandatory, but it certainly can make a major difference in an event like clock.

I'm surprised at how well received the notation is for competitors in Europe, because feelings are very mixed in my region.  It's not a matter of laziness, but people are seemingly very slow/inaccurate.  Some recent examples:

New Albany 2013 - Many new competitors were pulled in to scramble clock, as everyone who knew how to scramble was competing.  It took a significant amount of time (20-30 minutes) for me to complete my average, and I didn't even do all five solves since I had a DNF average.  I finally just shooed all of the new scramblers at the table, as they would more often than not get the scramble wrong.

Canadian Open 2013 - Similar situation, not as terrible as New Albany.  Dave had taught Forte and someone else I cannot remember how to scramble clock on the new notation, and it took a significant amount of time to get my average through so I could scramble again.  

UIUC Fall 2013 - Ilkyoo tried to recruit Kennan LeJeune to scramble clock for me before the event started, and so I walked him through an example scramble to ensure he understood all of the notation.  After failing to scramble a single clock correctly after 3-4 tries, he gave up and thus Ilkyoo decided to drop the event to scramble.  

The main points I dislike about the notation (besides the fact that I'm slower at it) are:
1. The pin positions are encoded into one or two letters rather than being spelled out by d and U.  While I think the current notation appears nicer, this encoding can become lost on some competitors, and lead to several errors in scrambling.
2. The wheel that is turned is always the up wheel.  While this seems to be an advantage, I think that this can also lead to several errors, as the scrambler may be confused as the up wheel changes throughout the scramble.  It becomes more apparent when down wheels and up wheels are used, as the scrambler will learn that the wheels of the same type are moving together.
3. I've seen so many new scramblers forget to do the flip.  A couple times I seen competitors receive clocks with an entire cross solved as a result of this, only to have it returned to the scrambling table later.  I have even had to do this myself at the Canadian Open.  

In my opinion, both scrambling methods have their ups and downs, so I see them as relatively equal.  But since Jaap is more known and can be scrambled faster by those that practice clock, why not go with this notation?  I'd feel better if we started to see other timers/scramblers adopt WCA notation, but for me this is much less desirable than just going back to Jaap.

**Comment by SAuroux** [comment] 2013-12-12 09:18
Would you mind simply starting a thread+survey on Speedsolving.com?

2013/12/12 KitClement notifications@github.com

**Comment by lgarron** [comment] 2013-12-12 10:05
I was going to request something else:
- Would someone be willing to search through the Delegate list archives for
  comments about clock scrambling to see how it actually went over this year?

»Lucas Garron

**Comment by KitClement** [comment] 2013-12-12 16:02
Rafael from Sao Paolo Open: "I found the clock scrambles notation much easier to execute now, but it is still a problem to scramble clocks because some of them come with very loose pins. I advised one of the competitors that in the next competition I will not allow his clock because we always had to scramble it twice or even 3 times."

Vidar from Norwegian Open: "Nobody knew how to scramble clock!?! This was the first competition where we used TNoodle for  clock scrambles. I as the delegate should definitely know how to scramble clock, but I did not Saturday morning. We decided to do clock later. I read about how to scramble the clock, and we did it on Sunday without any problem for anyone. Scrambling clock is still not hard, but a little different than what I remember it was. Also the regulations describe this really well, so the only one to blame is me as a Norwegian delegate."

Oliver from Austrian Big Cube Day: "Against all efforts we could not manage to do one group for Rubik’s Clock final. Everyone who could scramble this puzzle participated in the final, which made it
impossible to have one group. Fortunately we were prepared with 2 sheets of 
scrambles, so we had 2 groups. I am absolutely against this in any other case, but this 
time there was no other option. (1h+)" 

Responses to this report:
- Lorenzo: "Yeah, the same happened in Italy too. It's always the same story, nobody "can scramble" a clock. That's why I decided to hold the Rubik's Clock just once a year..."
- Ardianto: "They actually can scramble clocks or we can teach them in few minutes, but in my experience it takes them so long to scramble just a clock."
- Oliver: "That was my biggest worry as well. When you ask someone if he can scramble clock by the new notation and the answer is "There is a new notation?", I don't want them to take care of a final. We wanted to have someone to scramble me or Nikolett Placskó first, since we can then scramble everyone else pretty fast, but couldn't find anyone. Teaching them was also not an option 5 minutes prior to the final. (In their defense, most of them did not want originally compete in clock, but since we needed 16 competitors to have 3 rounds, they kindly agreed to competet, letting many more competitors having more fun.)"
- Hung: "Most of people do not know that WCA had a new notation of clock because lots of computer timer like qqtimer still using the old one. I like the old one, since I have already familiar to it. But the new one is more easy to learn for a beginner."

Ilkyoo at Korean Style: "The main bottleneck of the competition was Rubik's Clock. Even with three scramblers, we had to find more people to be scramblers since not all timers were saturated. "

Oliver, responding to Fortaleza Open: "For me it is really strange to see people not being able to scramble their favorite puzzle, the cubers I know usually practice using WCA scrambles if any. (One exception might be Rubik's Clock, as of now I am not aware of any online timer having the updated WCA scramble for that puzzle.)"

Vincent from Berkeley Summer: "Rubik's Clock suffered from a dearth of experienced scramblers, and further fell behind."

Jim from New Albany: " I think from now on I'm going to ask that organizers who hold clock be willing to scramble every puzzle themselves.  Nightmare to get those scrambled... lots of people solve, not many scramble quickly."

Matteo from Florence Open: "Clock was a problem because only two people (who weren't competing) did know how to scramble it but they were very slow."

Lars from Zonhoven Open: "The competition ran quite smoothly, but we ran behind on schedule on Saturday mostly because of the Clock event taking quite long. It seemed people needed to get used to the new scramble notation and this slowed us down."

Daniel from Edinburgh Open: " I am not entirely happy with the new clock notation though, although this may be down to lack of experience using it. It just seems too drawn out by having to do edges on one side then flip then do edges on the other side."

That's all I could find by just doing a quick search of the google group.

**Comment by KitClement** [comment] 2013-12-12 16:10
Also, as a secondary proposal, it wouldn't be difficult at all to display both notations.  I know that this is not in line with the WRC's goal to simplify the regulations/scrambles, but I figured I'd show my work on this anyways.  Here's some Maple output I have from when I tried to find a matrix that would transfer one of the notations to the other:

https://www.dropbox.com/sh/c9vhwyv4qnst9fq/S6ARyESHr8/Clock%20Scrambling%20Transformation.pdf

The numbering system used here is integers mod 12, so the numbers all correspond to how many clockwise 30 degree turns you make.  Thus, a 8 would correspond with a -4 turn.

The first 14 x 28 matrix (2) sets up the two bases, where the first 14 x 14 block represents old notation and the second 14 x 14 block represents the new notation.  Row reduction on this matrix will provide the desired transformation matrix in the second 14 x 14 block (3).

I then do an example to show how the matrix transforms the notation.  (4) gives a vector representation of a new scramble by simply putting all of the numbers from the scramble in order.  When you multiply the matrix by this vector, you get a vector that is all the numbers for the old notation in order (5).  Both scrambles can be verified to be identical.

**Comment by SAuroux** [comment] 2013-12-12 16:26
So the problem just seems to be that people are or were not used to the new
notation, the missing integration in commonly used timers and the fact,
that most people just can't scramble clocks, which was exactly the same
issue with the old notation (maybe even worse).

I really see no reason to go back and still propose to do some lobby work
to get it integrated in timers. Someone should work with Michael Gottlieb
to get it implemented in qqtimer (see:
http://www.speedsolving.com/forum/showthread.php?43327-WCA-Clock-Notation-Discussion&p=884811&viewfull=1#post884811
)

2013/12/12 KitClement notifications@github.com

**Comment by SAuroux** [comment] 2013-12-12 20:53
<< Is each pin up or down with probability 1/2, or does each collective
state of all four pins have equal probability? >>

That's exactly the same ;)

2013/12/12 KitClement notifications@github.com

**Comment by KitClement** [comment] 2013-12-12 21:09
Yeah, blonde moment for me, that's why I deleted that post. :P  

I've revived the thread from speedsolving on clock notation, hopefully Michael sees that response.

**Comment by lgarron** [comment] 2013-12-27 16:04
The Board vote is currently 3 for keeping the new, 1 for returning to old, and 1 missing vote.
In order to avoid unnecessary changes, I'm going to mark this `2014-wontfix`.

However, I'm starting to think that having the old scramble notation below the new one on the scramble pages is really quite okay, and should make everyone happy. We can still pursue that without changing the official notation.

**Comment by KitClement** [comment] 2013-12-27 16:58
I definitely like this resolution.  :)
For a scramble already generated in new notation, the translation from one
to the other is as follows: (simplification of my document I posted earlier)

UR(a)+ DR(b)+ DL(c)+ UL(d)+ U(e)+ R(f)+ D(g)+ L(h)+ ALL(i)+ y2 U(j)+ R(k)+
D(l)+ L(m)+ ALL(n)+

(a+d+e, -l) (a+b+f, -k) (b+c+g, -j) (c+d+h, -m) / (-b) (-c) (-d) (-a) / (i)
(-n)

I'd imagine this should be easy to implement if we do want to do this.

## 

Christopher Clement
University of Michigan Rackham | Applied Statistics MA

**Comment by Claster** [comment] 2014-01-03 06:59
Ba-dum-tss
![clock](https://f.cloud.github.com/assets/1568258/1837814/9e3f3374-7444-11e3-87ec-b12827eb17de.PNG)

**Comment by lgarron** [comment] 2014-12-19 09:26
Turning the status quo into a decision: The new notation is going to stay.

We're [happy to include the old notation below the new notation in TNoodle](https://github.com/cubing/tnoodle/issues/149) if people really want it. However, given that this is all volunteer work, someone other than Jeremy or me will have to take up the task.

**Closed as completed by lgarron** 2014-12-19 09:26 UTC
