### ISSUE TITLE
Rename events to match the ones in the web

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#461] opened 2017-09-08 18:59 UTC
The events defined in [9b)](https://www.worldcubeassociation.org/regulations/#9b) do not longer match the ones that we decided to display on the website.

**Comment by jfly** [comment] 2017-09-08 21:38
Dupe of #405? (Please reopen if I'm mistaken)

**Closed as completed by jfly** 2017-09-08 21:38 UTC

**Comment by AlbertoPdRF** [comment] 2017-09-08 21:52
Oh, my bad! Thanks @jfly
